{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-laeken
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/laeken_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/laeken/laeken_{{ version }}.tar.gz
  sha256: 22790f7157f23eb0b7b0b89e2ea53478fb3c0d15b5be8ad11525d3e6d5626cdc

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-boot
  run:
    - r-base
    - r-mass
    - r-boot

test:
  commands:
    - $R -e "library('laeken')"           # [not win]
    - "\"%R%\" -e \"library('laeken')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=laeken
  license: GPL-2.0-or-later
  summary: Estimation of indicators on social exclusion and poverty, as well as Pareto tail modeling for empirical income distributions.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: laeken
# Type: Package
# Title: Estimation of Indicators on Social Exclusion and Poverty
# Version: 0.5.1
# Date: 2020-02-05
# Depends: R (>= 3.2.0)
# Imports: boot, MASS
# Description: Estimation of indicators on social exclusion and poverty, as well as Pareto tail modeling for empirical income distributions.
# License: GPL (>= 2)
# Authors@R: c(person("Andreas", "Alfons", email = "alfons@ese.eur.nl", role = c("aut", "cre")), person("Josef", "Holzer", role = "aut"), person("Matthias", "Templ", role = "aut"), person("Alexander", "Haider", role = "ctb"))
# Author: Andreas Alfons [aut, cre], Josef Holzer [aut], Matthias Templ [aut], Alexander Haider [ctb]
# Maintainer: Andreas Alfons <alfons@ese.eur.nl>
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2020-02-05 08:17:58 UTC; andreas
# Repository: CRAN
# Date/Publication: 2020-02-05 14:40:15 UTC
