{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-laeken
  version: {{ version|replace("-", "_") }}

source:
  fn: laeken_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/laeken_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/laeken/laeken_{{ version }}.tar.gz
  sha256: 1aa94a1768969eb999f7a41212af2d8b2943b43a68a92f99c9f77929e19439a5

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-mass
    - r-boot
  run:
    - r-base
    - r-mass
    - r-boot

test:
  commands:
    - $R -e "library('laeken')"           # [not win]
    - "\"%R%\" -e \"library('laeken')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=laeken
  license: GPL (>= 2)
  summary: Estimation of indicators on social exclusion and poverty, as well as Pareto tail modeling
    for empirical income distributions.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
