travis:
  secure:
    BINSTAR_TOKEN: KEIgcVk9mFllH8absub/GAq1f0RBxbM/QkWZ1jql5KwPjFxdnwN+EgM609U60j2pCLaY5k8yTRkiJlt3uxuyqEreTasO1TLxu4M/eaa9FBgGXmOQzeXJVWf+8cxHfQw7v1kENhnnMSvOQYFDVzozcNv5gh1SB7ZrEFJOL2EhGqDceiO1T6ViTOeo0GUchvo/yOIu4uduH7uthsAt66/Lr01B4HGDl7Q78U7dYqsfjRBqojwudZKrzB+UPssL6GwS7C4YW8yVU7dbp1bMUz9rp/kQZerU9XKZJ4j5L8P8elOw7P40NBznWeVg74vtmCe+ECVb+0Js3ASE0AUYEq11bpX537wJc7TcgWZnUehFo2I2C9BiS5m7/XbOzJ+YuQM/9t3ZG/U6ajw7iFElSrWze/WkDRHeRJaMLsOWdD/9cWCwS3XK6YIwoz3fGticm4hyq6CMwP2hktsi5GGZKgppeEhrwlUgSolCCT4Xyl615mfF+43nmGvxto6aQydEkAnCBvmLT+m9rn+/FZUyksXabmKu2V63AHw/75PzABASqjusjPwJioMLBBEkU7+TirkIKULu7RjiqT/mBg4UjldT/ALPz/er16t1aX+vbZWWxV3o3ZIUhrA/aaM3xKVqqtubaUZwkRH5JJbW+R2edldPYm4U2+FPXc2fgIt1a2nkwo4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
